const DEFAULT_MEATS=[{id:'tomahawk',name:'Tomahawk',price:7.90},{id:'fiorentina',name:'Fiorentina',price:8.50},{id:'costata',name:'Costata',price:6.90},{id:'tbone',name:'T-Bone',price:7.50},{id:'controfiletto',name:'Controfiletto',price:8.90},{id:'filetto',name:'Filetto',price:9.50},{id:'picanha',name:'Picanha',price:6.80},{id:'entrecote',name:'Entrecôte',price:7.20},{id:'wagyu',name:'Wagyu',price:18.00},{id:'canguro',name:'Canguro',price:6.50},{id:'agnello',name:'Agnello',price:6.90},{id:'altro',name:'Altro',price:0}];
const DEFAULT_TABLES=Array.from({length:20},(_,i)=>String(i+1));
let state=loadState();let selectedTable=state.tables[0];let selectedMeat=state.meats[0]?.id;let adminUnlocked=false;
const $=id=>document.getElementById(id);const euro=n=>(n||0).toLocaleString('it-IT',{style:'currency',currency:'EUR'});const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
function loadState(){const saved=localStorage.getItem('monangMeatState');if(saved)try{return JSON.parse(saved)}catch{}return{meats:DEFAULT_MEATS,tables:DEFAULT_TABLES,orders:[],pin:'1234'}}
function save(){localStorage.setItem('monangMeatState',JSON.stringify(state));window.dispatchEvent(new Event('storage'))}
function today(){return new Date().toLocaleDateString('it-IT')}function now(){return new Date().toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}
function currentMeat(){return state.meats.find(m=>m.id===selectedMeat)||state.meats[0]}function currentTotal(){const w=parseFloat($('weightInput').value)||0;const m=currentMeat();return w*m.price/100}
function renderAll(){renderTables();renderMeats();renderCalc();renderOrders();renderAdmin();}
function renderTables(){let h='';state.tables.forEach(t=>h+=`<button class="${t===selectedTable?'active':''}" data-table="${t}">${t}</button>`);$('tablesGrid').innerHTML=h;$('selectedTableLabel').textContent=selectedTable||'-';document.querySelectorAll('[data-table]').forEach(b=>b.onclick=()=>{selectedTable=b.dataset.table;renderTables()})}
function renderMeats(){let h='';state.meats.forEach(m=>h+=`<button class="${m.id===selectedMeat?'active':''}" data-meat="${m.id}">🥩<br>${m.name}</button>`);$('meatsGrid').innerHTML=h;document.querySelectorAll('[data-meat]').forEach(b=>b.onclick=()=>{selectedMeat=b.dataset.meat;renderMeats();renderCalc()})}
function renderCalc(){const m=currentMeat();$('priceLabel').textContent=euro(m?.price||0);$('totalLabel').textContent=euro(currentTotal())}
function addOrder(){const weight=parseFloat($('weightInput').value)||0;const meat=currentMeat();if(!selectedTable)return alert('Seleziona tavolo');if(!meat)return alert('Seleziona carne');if(weight<=0)return alert('Inserisci peso');state.orders.unshift({id:uid(),date:today(),time:now(),table:selectedTable,meatId:meat.id,meatName:meat.name,price:meat.price,weight,total:weight*meat.price/100,status:'pending'});save();$('weightInput').value='';renderAll();showView('cassa')}
function renderOrders(){const todays=state.orders.filter(o=>o.date===today());const pending=todays.filter(o=>o.status==='pending');const done=todays.filter(o=>o.status==='done');$('pendingCount').textContent=pending.length;$('doneCount').textContent=done.length;$('pendingBadge').textContent=pending.length;$('dayTotal').textContent=euro(todays.reduce((s,o)=>s+o.total,0));$('pendingList').innerHTML=pending.length?pending.map(orderHtml).join(''):'<p class="hint">Nessuna carne da inserire.</p>';$('doneList').innerHTML=done.length?done.map(orderHtml).join(''):'<p class="hint">Nessuna carne inserita.</p>';document.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>markDone([b.dataset.done]));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('Eliminare questa riga?')){state.orders=state.orders.filter(o=>o.id!==b.dataset.del);save();renderAll()}})}
function orderHtml(o){return `<div class="order ${o.status==='done'?'done':''}"><input type="checkbox" class="orderCheck" value="${o.id}"><div class="tableNum"><small>TAVOLO</small>${o.table}</div><div><div class="meatName">${o.meatName}${o.qty?` ×${o.qty}`:''}</div><div class="meta">${Math.round(o.weight)} g · ${euro(o.price)}/100g · ${o.time}</div></div><div class="amount">${euro(o.total)}</div><div class="orderActions">${o.status==='pending'?`<button class="btn green" data-done="${o.id}">✅ Inserito</button>`:''}<button class="btn secondary" data-del="${o.id}">Elimina</button></div></div>`}
function selectedOrderIds(){return [...document.querySelectorAll('.orderCheck:checked')].map(c=>c.value)}
function markDone(ids){if(!ids.length)return alert('Seleziona almeno una riga');state.orders=state.orders.map(o=>ids.includes(o.id)?{...o,status:'done'}:o);save();renderAll()}
function mergeSelected(){const ids=selectedOrderIds();if(ids.length<2)return alert('Seleziona almeno due righe da unire');const items=state.orders.filter(o=>ids.includes(o.id)&&o.status==='pending');if(items.length<2)return alert('Puoi unire solo righe da inserire');const first=items[0];const same=items.every(o=>o.table===first.table&&o.meatName===first.meatName&&Number(o.price)===Number(first.price));if(!same&&!confirm('Le righe non sono identiche per tavolo/carne/prezzo. Vuoi unirle lo stesso?'))return;const merged={...first,id:uid(),weight:items.reduce((s,o)=>s+Number(o.weight),0),total:items.reduce((s,o)=>s+Number(o.total),0),qty:items.reduce((s,o)=>s+(o.qty||1),0),time:now()};state.orders=state.orders.filter(o=>!ids.includes(o.id));state.orders.unshift(merged);save();renderAll()}
function renderAdmin(){if(!adminUnlocked)return;$('tablesInput').value=state.tables.join(', ');$('meatsAdmin').innerHTML=state.meats.map(m=>`<div class="adminMeat"><input data-name="${m.id}" value="${m.name}"><input data-price="${m.id}" type="number" step="0.01" value="${m.price}"><button class="btn danger" data-remove="${m.id}">X</button></div>`).join('');document.querySelectorAll('[data-name]').forEach(i=>i.onchange=()=>{const m=state.meats.find(x=>x.id===i.dataset.name);m.name=i.value;save();renderAll()});document.querySelectorAll('[data-price]').forEach(i=>i.onchange=()=>{const m=state.meats.find(x=>x.id===i.dataset.price);m.price=parseFloat(i.value)||0;save();renderAll()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(confirm('Eliminare carne?')){state.meats=state.meats.filter(m=>m.id!==b.dataset.remove);selectedMeat=state.meats[0]?.id;save();renderAll()}})}
function showView(v){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===v));document.querySelectorAll('.view').forEach(s=>s.classList.remove('active'));$(`view-${v}`).classList.add('active')}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>showView(t.dataset.view));$('weightInput').oninput=renderCalc;$('clearWeight').onclick=()=>{$('weightInput').value='';renderCalc()};$('newCalc').onclick=()=>{$('weightInput').value='';renderCalc()};$('sendOrder').onclick=addOrder;$('mergeSelected').onclick=mergeSelected;$('markSelectedDone').onclick=()=>markDone(selectedOrderIds());$('unlockAdmin').onclick=()=>{if($('pinInput').value===state.pin){adminUnlocked=true;$('pinPanel').classList.add('hidden');$('adminPanel').classList.remove('hidden');renderAdmin()}else alert('PIN errato')};$('addMeat').onclick=()=>{const name=$('newMeatName').value.trim();const price=parseFloat($('newMeatPrice').value)||0;if(!name)return alert('Inserisci nome carne');const id=name.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-'+uid().slice(-3);state.meats.push({id,name,price});$('newMeatName').value='';$('newMeatPrice').value='';save();renderAll()};$('saveTables').onclick=()=>{state.tables=$('tablesInput').value.split(',').map(x=>x.trim()).filter(Boolean);selectedTable=state.tables[0];save();renderAll()};$('savePin').onclick=()=>{if(!$('pinNew').value)return;state.pin=$('pinNew').value;save();$('pinNew').value='';alert('PIN salvato')};$('resetDay').onclick=()=>{if(confirm('Azzerare la giornata di oggi?')){state.orders=state.orders.filter(o=>o.date!==today());save();renderAll()}};window.addEventListener('storage',()=>{state=loadState();renderAll()});
if(window.MONANG_FIREBASE_CONFIG){$('connection').textContent='CONFIG FIREBASE PRESENTE (da collegare)'}
renderAll();
