import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getFirestore, doc, getDoc, setDoc, updateDoc, collection, addDoc, deleteDoc, onSnapshot, query, where, orderBy, serverTimestamp, writeBatch } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';

const app = initializeApp(window.firebaseConfig);
const db = getFirestore(app);

const DEFAULT = {
  pin:'1234',
  tables:[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
  meats:[
    {id:'tomahawk',name:'Tomahawk',price:7.90},
    {id:'fiorentina',name:'Fiorentina',price:8.50},
    {id:'costata',name:'Costata',price:6.90},
    {id:'tbone',name:'T-Bone',price:7.50},
    {id:'controfiletto',name:'Controfiletto',price:8.90},
    {id:'filetto',name:'Filetto',price:9.50},
    {id:'picanha',name:'Picanha',price:6.50},
    {id:'entrecote',name:'Entrecôte',price:7.20},
    {id:'canguro',name:'Canguro',price:6.50},
    {id:'agnello',name:'Agnello',price:6.90},
    {id:'wagyu',name:'Wagyu',price:18.00},
    {id:'altro',name:'Altro',price:0}
  ]
};
let settings = structuredClone(DEFAULT);
let selectedTable = 1, selectedMeatId = 'tomahawk', orders = [], adminUnlocked=false;
const $ = id => document.getElementById(id);
const euro = n => new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n||0));
const today = () => new Date().toISOString().slice(0,10);
const slug = s => (s||'carne').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString(36).slice(-4);
function toast(t){ const d=document.createElement('div'); d.className='toast'; d.textContent=t; document.body.appendChild(d); setTimeout(()=>d.remove(),2200); }
function selectedMeat(){ return settings.meats.find(m=>m.id===selectedMeatId) || settings.meats[0] || {name:'-',price:0,id:'x'}; }
function calcTotal(){ const w=Number($('weightInput').value||0); return Math.round((w/100)*Number(selectedMeat().price||0)*100)/100; }
function updateCalc(){ const m=selectedMeat(); $('priceLabel').textContent=euro(m.price); $('totalLabel').textContent=euro(calcTotal()); }
async function ensureSettings(){ const ref=doc(db,'settings','main'); const snap=await getDoc(ref); if(!snap.exists()) await setDoc(ref,DEFAULT); }
function renderTables(){ const box=$('tablesGrid'); box.innerHTML=''; settings.tables.forEach(t=>{ const b=document.createElement('button'); b.className='tile '+(Number(t)===Number(selectedTable)?'active':''); b.textContent=t; b.onclick=()=>{selectedTable=t; renderTables(); $('selectedTableLabel').textContent=t;}; box.appendChild(b); }); $('selectedTableLabel').textContent=selectedTable; $('tablesInput').value=settings.tables.join(', '); }
function renderMeats(){ const box=$('meatsGrid'); box.innerHTML=''; settings.meats.forEach(m=>{ const b=document.createElement('button'); b.className='tile meat '+(m.id===selectedMeatId?'active':''); b.innerHTML=`${m.name}<br><small>${euro(m.price)}/100g</small>`; b.onclick=()=>{selectedMeatId=m.id; renderMeats(); updateCalc();}; box.appendChild(b); }); updateCalc(); }
function renderAdmin(){ const box=$('meatsAdmin'); box.innerHTML=''; settings.meats.forEach(m=>{ const row=document.createElement('div'); row.className='meatAdminRow'; row.innerHTML=`<input value="${m.name.replaceAll('"','&quot;')}" data-k="name"><input type="number" step="0.01" value="${m.price}" data-k="price"><button class="btn danger">X</button>`; const [name,price,del]=row.children; name.onchange=price.onchange=async()=>{ m.name=name.value.trim()||m.name; m.price=Number(price.value||0); await updateDoc(doc(db,'settings','main'),{meats:settings.meats}); toast('Carne aggiornata'); }; del.onclick=async()=>{ if(confirm('Eliminare questa carne?')){ settings.meats=settings.meats.filter(x=>x.id!==m.id); await updateDoc(doc(db,'settings','main'),{meats:settings.meats}); } }; box.appendChild(row); }); }
function renderOrders(){ const pending=orders.filter(o=>o.status!=='done'); const done=orders.filter(o=>o.status==='done'); $('pendingBadge').textContent=pending.length; $('pendingCount').textContent=pending.length; $('doneCount').textContent=done.length; $('dayTotal').textContent=euro(done.reduce((s,o)=>s+Number(o.total||0),0)); renderList('pendingList', pending, true); renderList('doneList', done, false); }
function renderList(id, list, pending){ const box=$(id); box.innerHTML=''; if(!list.length){ box.innerHTML='<div class="card hint">Nessun elemento</div>'; return; } list.forEach(o=>{ const d=document.createElement('div'); d.className='order '+(pending?'pending':'done'); d.innerHTML=`<input type="checkbox" data-id="${o.id}"><div class="ordTable"><small>TAVOLO</small><br><strong>${o.table}</strong></div><div class="ordInfo"><strong>${o.meatName}${o.count>1?' ×'+o.count:''}</strong><br>${o.weight} g <small>${euro(o.price)}/100g</small></div><div class="ordTotal"><strong>${euro(o.total)}</strong><br><small>${o.time||''}</small></div>${pending?'<div class="orderActions"><button class="btn secondary edit">✏️ Modifica</button><button class="btn green doneBtn">✅ Inserito</button></div>':''}`; if(pending){ d.querySelector('.doneBtn').onclick=()=>markDone([o.id]); d.querySelector('.edit').onclick=()=>editOrder(o); } box.appendChild(d); }); }
async function addOrder(){ const w=Number($('weightInput').value||0), m=selectedMeat(); if(!selectedTable) return toast('Seleziona tavolo'); if(!m) return toast('Seleziona carne'); if(!w || w<=0) return toast('Inserisci il peso'); const n=new Date(); await addDoc(collection(db,'orders'),{day:today(),table:Number(selectedTable),meatId:m.id,meatName:m.name,price:Number(m.price),weight:w,total:calcTotal(),status:'pending',count:1,time:n.toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'}),createdAt:serverTimestamp(),updatedAt:serverTimestamp()}); $('weightInput').value=''; updateCalc(); toast('Inviato alla cassa'); }
async function markDone(ids){ const b=writeBatch(db); ids.forEach(id=>b.update(doc(db,'orders',id),{status:'done',updatedAt:serverTimestamp()})); await b.commit(); }
function selectedIds(){ return [...document.querySelectorAll('#pendingList input[type=checkbox]:checked')].map(x=>x.dataset.id); }
async function mergeSelected(){ const ids=selectedIds(); if(ids.length<2) return toast('Seleziona almeno 2 righe'); const sel=orders.filter(o=>ids.includes(o.id)); const first=sel[0]; const ok=sel.every(o=>o.table===first.table && o.meatName===first.meatName && Number(o.price)===Number(first.price) && o.status!=='done'); if(!ok) return toast('Puoi unire solo stesso tavolo, carne e prezzo'); const totalW=sel.reduce((s,o)=>s+Number(o.weight||0),0); const total=sel.reduce((s,o)=>s+Number(o.total||0),0); const b=writeBatch(db); ids.forEach(id=>b.delete(doc(db,'orders',id))); await b.commit(); await addDoc(collection(db,'orders'),{day:today(),table:first.table,meatId:first.meatId,meatName:first.meatName,price:first.price,weight:totalW,total:Math.round(total*100)/100,status:'pending',count:sel.reduce((s,o)=>s+Number(o.count||1),0),time:new Date().toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'}),createdAt:serverTimestamp(),updatedAt:serverTimestamp()}); toast('Righe unite'); }
function editOrder(o){ selectedTable=o.table; selectedMeatId=o.meatId; $('weightInput').value=o.weight; switchView('griglia'); renderTables(); renderMeats(); updateCalc(); toast('Riaperto in griglia. Correggi e invia di nuovo. Ricorda di eliminare la vecchia riga in cassa se serve.'); }
function switchView(v){ document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===v)); document.querySelectorAll('.view').forEach(s=>s.classList.remove('active')); $('view-'+v).classList.add('active'); }
function bind(){ document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchView(b.dataset.view)); $('weightInput').oninput=updateCalc; $('clearWeight').onclick=()=>{$('weightInput').value='';updateCalc();}; $('newCalc').onclick=()=>{$('weightInput').value='';updateCalc();}; $('sendOrder').onclick=addOrder; $('mergeSelected').onclick=mergeSelected; $('markSelectedDone').onclick=()=>{ const ids=selectedIds(); if(!ids.length) return toast('Seleziona una riga'); markDone(ids); }; $('unlockAdmin').onclick=()=>{ if($('pinInput').value===settings.pin){ adminUnlocked=true; $('pinPanel').classList.add('hidden'); $('adminPanel').classList.remove('hidden'); } else toast('PIN errato'); }; $('addMeat').onclick=async()=>{ const name=$('newMeatName').value.trim(); const price=Number($('newMeatPrice').value||0); if(!name) return toast('Scrivi il nome'); settings.meats.push({id:slug(name),name,price}); await updateDoc(doc(db,'settings','main'),{meats:settings.meats}); $('newMeatName').value=''; $('newMeatPrice').value=''; }; $('saveTables').onclick=async()=>{ const arr=$('tablesInput').value.split(/[ ,;\n]+/).map(x=>Number(x)).filter(Boolean); if(!arr.length) return toast('Inserisci tavoli'); settings.tables=arr; await updateDoc(doc(db,'settings','main'),{tables:arr}); }; $('savePin').onclick=async()=>{ const p=$('pinNew').value.trim(); if(p.length<3) return toast('PIN troppo corto'); await updateDoc(doc(db,'settings','main'),{pin:p}); $('pinNew').value=''; toast('PIN aggiornato'); }; $('resetDay').onclick=async()=>{ if(!confirm('Azzerare tutti i dati di oggi?'))return; const b=writeBatch(db); orders.forEach(o=>b.delete(doc(db,'orders',o.id))); await b.commit(); }; }
async function init(){ bind(); try{ await ensureSettings(); onSnapshot(doc(db,'settings','main'),snap=>{ settings={...DEFAULT,...(snap.data()||{})}; if(!settings.meats.find(m=>m.id===selectedMeatId)) selectedMeatId=settings.meats[0]?.id; renderTables(); renderMeats(); renderAdmin(); $('connection').textContent='ONLINE - SINCRONIZZATO'; }); const q=query(collection(db,'orders'),where('day','==',today()),orderBy('createdAt','desc')); onSnapshot(q,snap=>{ orders=snap.docs.map(d=>({id:d.id,...d.data()})); renderOrders(); },err=>{ console.error(err); $('connection').textContent='ERRORE DATABASE'; toast('Controlla le regole Firestore'); }); }catch(e){ console.error(e); $('connection').textContent='ERRORE FIREBASE'; toast('Firebase non collegato: controlla config e regole'); renderTables(); renderMeats(); renderAdmin(); } }
init();
